# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
User.create(first_name: 'Tom', last_name: 'Smith', username: 'tsmith', email: 'tsmith@smith.com', password: 'tsmith1')
User.create(first_name: 'George', last_name: 'Navas', username: 'gnavas', email: 'gannavas@gmail.com', password: 'gnavas1')
User.create(first_name: 'Ryan', last_name: 'Wilson', username: 'rwilson', email: 'rycwilson@gmail.com', password: 'rwilson1')
User.create(first_name: 'Jenni', last_name: 'Choi', username: 'jchoi', email: 'jenni0729@gmail.com', password: 'jchoi1')
User.create(first_name: 'Mary', last_name: 'Kim', username: 'mkim', email: 'jac2292@caa.columbia.edu', password: 'mkim1')
User.create(first_name: 'Kevin', last_name: 'Ortiz', username: 'kortiz', email: 'kotiz@ortiz.com', password: 'kortiz1')
User.create(first_name: 'Eugene', last_name: 'Choi', username: 'echoi', email: 'echoi@choi.com', password: 'echoi1')
User.create(first_name: 'Jackie', last_name: 'Sasscer', username: 'jsasscer', email: 'jsasscer@gmail.com', password: 'jsasscer1')
User.create(first_name: 'Erin', last_name: 'Huie', username: 'ehuie', email: 'ehuie@gmail.com', password: 'ehuie1')
User.create(first_name: 'Peggy', last_name: 'Little', username: 'plittle', email: 'plittle@gmail.com', password: 'plittle1')

Companion.create(first_name: 'Tom', last_name: 'Smith', email: 'tsmith@smith.com')
Companion.create(first_name: 'George', last_name: 'Navas', email: 'gannavas@gmail.com')
Companion.create(first_name: 'Ryan', last_name: 'Wilson', email: 'rycwilson@gmail.com')
Companion.create(first_name: 'Jenni', last_name: 'Choi', email: 'jenni0729@gmail.com')
Companion.create(first_name: 'Mary', last_name: 'Kim', email: 'jac2292@caa.columbia.edu')
Companion.create(first_name: 'Kevin', last_name: 'Ortiz', email: 'kotiz@ortiz.com')
Companion.create(first_name: 'Eugene', last_name: 'Choi', email: 'echoi@choi.com')
Companion.create(first_name: 'Jackie', last_name: 'Sasscer', email: 'jsasscer@gmail.com')
Companion.create(first_name: 'Erin', last_name: 'Huie', email: 'ehuie@gmail.com')
Companion.create(first_name: 'Peggy', last_name: 'Little', email: 'plittle@gmail.com')

Itinerary.create(origin: 'San Francisco', destination: 'Baltimore', name: 'Bmore Trip', user_id: 1)
Itinerary.create(origin: 'Baltimore', destination: 'San Francisco', name: 'SF Trip', user_id: 2 )
Itinerary.create(origin: 'San Francisco', destination: 'London', name: 'London Trip', user_id: 3)

Activity.create(location: 'Alcatraz', name: 'Alcatraz Trip', itinerary_id: 1)
Activity.create(location: 'Ghirardelli Square', name: 'Ghirardelli Trip', itinerary_id: 1)
Activity.create(location: 'National Aquarium', name: 'See Fishies', itinerary_id: 2)
Activity.create(location: 'Federal Hill', name: 'Fed Hill Trip', itinerary_id: 2)
Activity.create(location: 'Globe Theater', name: 'Globe Theater Trip', itinerary_id: 3)
Activity.create(location: 'Buckingham Palace', name: 'Buckingham Trip', itinerary_id: 3)

Companions_itinerary.create(companion_id: 1 , itinerary_id: 1)
Companions_itinerary.create(companion_id: 2 , itinerary_id: 1)
Companions_itinerary.create(companion_id: 3 , itinerary_id: 1)
Companions_itinerary.create(companion_id: 4 , itinerary_id: 1)
Companions_itinerary.create(companion_id: 5 , itinerary_id: 2)
Companions_itinerary.create(companion_id: 6 , itinerary_id: 2)
Companions_itinerary.create(companion_id: 7 , itinerary_id: 2)
Companions_itinerary.create(companion_id: 8 , itinerary_id: 2)
Companions_itinerary.create(companion_id: 9 , itinerary_id: 3)
Companions_itinerary.create(companion_id: 10 , itinerary_id: 3)

Companions_activity.create(activity_id: 1, companion_id: 1)
Companions_activity.create(activity_id: 2, companion_id: 2)
Companions_activity.create(activity_id: 1, companion_id: 3)
Companions_activity.create(activity_id: 2, companion_id: 4)
Companions_activity.create(activity_id: 3, companion_id: 5)
Companions_activity.create(activity_id: 4, companion_id: 6)
Companions_activity.create(activity_id: 3, companion_id: 7)
Companions_activity.create(activity_id: 4, companion_id: 8)
Companions_activity.create(activity_id: 5, companion_id: 9)
Companions_activity.create(activity_id: 6, companion_id: 10)

Review.create(content: "Tom is the best person to travel with!", reviewable_type: "companion", reviewable_id: 1)
Review.create(content: "George is the best person to travel with!", reviewable_type: "companion", reviewable_id: 2)
Review.create(content: "Ryan is the best person to travel with!", reviewable_type: "companion", reviewable_id: 3)
Review.create(content: "Jenni is the best person to travel with!", reviewable_type: "companion", reviewable_id: 4)
Review.create(content: "Mary is the best person to travel with!", reviewable_type: "companion", reviewable_id: 5)
Review.create(content: "Kevin is the best person to travel with!", reviewable_type: "companion", reviewable_id: 6)
Review.create(content: "Eugene is the best person to travel with!", reviewable_type: "companion", reviewable_id: 7)
Review.create(content: "Jackie is the best person to travel with!", reviewable_type: "companion", reviewable_id: 8)
Review.create(content: "Erin is the best person to travel with!", reviewable_type: "companion", reviewable_id: 9)
Review.create(content: "Peggy is the best person to travel with!", reviewable_type: "companion", reviewable_id: 10)

Review.create(content: "Baltimore Rocks!", reviewable_type: "itinerary", reviewable_id: 1)
Review.create(content: "San Francisco Rocks!", reviewable_type: "itinerary", reviewable_id: 2)
Review.create(content: "London Rocks!", reviewable_type: "itinerary", reviewable_id: 3)

Review.create(content: "Love Alcatraz!", reviewable_type: "activity", reviewable_id: 1)
Review.create(content: "Love Ghirdelli Square!", reviewable_type: "activity", reviewable_id: 2)
Review.create(content: "Love National Aquarium!", reviewable_type: "activity", reviewable_id: 3)
Review.create(content: "Love Federal Hill!", reviewable_type: "activity", reviewable_id: 4)
Review.create(content: "Love Globe Theater!", reviewable_type: "activity", reviewable_id: 5)
Review.create(content: "Love Buckingham Palace!", reviewable_type: "activity", reviewable_id: 6)